// src/views/Home.vue
<template>
  <div>
    <h1>Pokémon Trainer Hub</h1>
    <p>
      Welcome, Trainer! Here you can explore your favorite Pokémon, check their
      stats, and prepare for your next big battle.
    </p>
    <img
      src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png"
      alt="Pikachu"
      width="200"
    />
    <div style="margin-top: 20px">
      <router-link to="/login">
        <button>Log In</button>
      </router-link>
      <router-link to="/signup" style="margin-left: 10px">
        <button>Sign Up</button>
      </router-link>
    </div>
  </div>
</template>

<script setup></script>

// src/views/Home.tsx
import React from 'react';
import { Link } from 'react-router-dom';

function Home() {
  return (
    <div className="container">
      <div className="row">
        <h1 className="col-12 mt-3">Pokémon Trainer Hub</h1>
      </div>

      <div className="row">
        <div className="col-12">
          <p>
            Welcome, Trainer! Here you can explore your favorite Pokémon, check
            their stats, and prepare for your next big battle.
          </p>
        </div>
      </div>

      <div className="row">
        <div className="col-12">
          <div className="image-container">
            <img
              src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png"
              alt="Pikachu"
              width="200"
            />
            <img
              src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png"
              alt="Bulbasaur"
              width="200"
            />
          </div>
        </div>
      </div>

      <div className="row">
        <div className="col-12" style={{ marginTop: '20px' }}>
          <Link to="/login">
            <button>🔑 Log In</button>
          </Link>
          <Link to="/signup" style={{ marginLeft: '10px' }}>
            <button>📝 Sign Up</button>
          </Link>
        </div>
      </div>
    </div>
  );
}

export default Home;
