// src/components/PokemonCard.vue
<template>
  <div class="pokemon-card mb-3">
    <div class="card-body">
      <div class="row">
        <div class="col-12 d-flex justify-content-between">
          <h5 v-if="!editing" class="card-title">{{ local.name }}</h5>
          <input v-else v-model="local.name" class="form-control" />
        </div>

        <div class="col-12">
          <p v-if="!editing" class="card-text">{{ local.comment }}</p>
          <textarea
            v-else
            v-model="local.comment"
            class="form-control"
          ></textarea>
        </div>

        <div class="col-12">
          <p class="card-text">❤️ {{ local.likes }} Likes</p>
        </div>

        <div class="col-12" v-if="!editing">
          <button @click="handleLike" class="btn btn-outline-primary me-2">
            👍 Like
          </button>
          <button @click="startEdit" class="btn btn-outline-warning me-2">
            ✏️ Edit
          </button>
          <button
            @click="$emit('delete', local.id)"
            class="btn btn-outline-danger"
          >
            🗑 Delete
          </button>
        </div>

        <div class="col-12" v-else>
          <button @click="saveEdit" class="btn btn-outline-success me-2">
            💾 Save
          </button>
          <button @click="cancelEdit" class="btn btn-outline-secondary">
            ❌ Cancel
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
const props = defineProps(['pokemon']);
const emit = defineEmits(['like', 'delete', 'edit']);

const editing = ref(false);
const local = ref({ ...props.pokemon });

const handleLike = () => {
  emit('like', local.value.id);
  local.value.likes++;
};

const startEdit = () => {
  editing.value = true;
};

const saveEdit = () => {
  emit('edit', local.value);
  editing.value = false;
};

const cancelEdit = () => {
  local.value = { ...props.pokemon };
  editing.value = false;
};
</script>

// src/components/PokemonCard.tsx
import React, { useState } from 'react';
import { Pokemon } from '../hooks/useDB';

interface PokemonCardProps {
  pokemon: Pokemon;
  onLike: (id: string) => void;
  onDelete: (id: string) => void;
  onEdit: (pokemon: Pokemon) => void;
}

function PokemonCard({ pokemon, onLike, onDelete, onEdit }: PokemonCardProps) {
  const [editing, setEditing] = useState(false);
  const [local, setLocal] = useState({ ...pokemon });

  const handleLike = () => {
    if (pokemon._id) {
      onLike(pokemon._id);
      setLocal({ ...local, likes: local.likes + 1 });
    }
  };

  const startEdit = () => {
    setEditing(true);
  };

  const saveEdit = () => {
    onEdit(local);
    setEditing(false);
  };

  const cancelEdit = () => {
    setLocal({ ...pokemon });
    setEditing(false);
  };

  return (
    <div className="pokemon-card mb-3">
      <div className="card-body">
        <div className="row">
          <div className="col-12 d-flex justify-content-between">
            {!editing ? (
              <h5 className="card-title">{local.name}</h5>
            ) : (
              <input
                value={local.name}
                onChange={(e) => setLocal({ ...local, name: e.target.value })}
                className="form-control"
              />
            )}
          </div>

          <div className="col-12">
            {!editing ? (
              <p className="card-text">{local.comment}</p>
            ) : (
              <textarea
                value={local.comment}
                onChange={(e) =>
                  setLocal({ ...local, comment: e.target.value })
                }
                className="form-control"
              />
            )}
          </div>

          <div className="col-12">
            <p className="card-text">❤️ {local.likes} Likes</p>
          </div>

          {!editing ? (
            <div className="col-12">
              <button
                onClick={handleLike}
                className="btn btn-outline-primary me-2"
              >
                👍 Like
              </button>
              <button
                onClick={startEdit}
                className="btn btn-outline-warning me-2"
              >
                ✏️ Edit
              </button>
              <button
                onClick={() => pokemon._id && onDelete(pokemon._id)}
                className="btn btn-outline-danger"
              >
                🗑 Delete
              </button>
            </div>
          ) : (
            <div className="col-12">
              <button
                onClick={saveEdit}
                className="btn btn-outline-success me-2"
              >
                💾 Save
              </button>
              <button
                onClick={cancelEdit}
                className="btn btn-outline-secondary"
              >
                ❌ Cancel
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default PokemonCard;
